site_name: RustyCord
site_description: A modern, fast, and easy-to-use Discord bot library for Rust - DEVELOPMENT VERSION - NOT PRODUCTION READY
site_author: Hrithik Dhakrey
site_url: https://rustycord.iamdhakrey.dev

repo_name: iamdhakrey/rustycord
repo_url: https://github.com/iamdhakrey/rustycord
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/rustycord-logo.png
  favicon: images/rustycord-favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
    logo: material/robot  # Alternative to image logo
    edit: material/pencil
    view: material/eye
    tag:
      default: material/tag
      rust: simple/rust
      discord: fontawesome/brands/discord
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search

extra:
  announce: |
    🚨 <strong>DEVELOPMENT WARNING</strong>: rustycord is in heavy development and NOT ready for production use. 
    APIs change frequently and features are incomplete. Use only for learning and experimentation.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iamdhakrey
      name: GitHub Profile
    - icon: fontawesome/brands/github-alt
      link: https://github.com/iamdhakrey/rustycord
      name: rustycord Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rustycord
      name: Discord Community
    - icon: simple/rust
      link: https://crates.io/crates/rustycord
      name: Crates.io Package
    - icon: material/book-open
      link: https://docs.rs/rustycord
      name: API Documentation
  version:
    provider: github
    repo: iamdhakrey/rustycord
    branch: main
  status:
    development: true
    production_ready: false

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - "📊 Development Status": development-status.md
  - "🚀 Getting Started":
    - "⚙️ Installation": getting-started/installation.md
    - "🤖 Your First Bot": getting-started/first-bot.md
  - "📖 User Guide":
    - "🔧 Bot Basics": user-guide/bot-basics.md
    - "⌨️ Prefix Commands": user-guide/prefix-commands.md
  - "💡 Examples":
    - "🎯 Basic Bot": examples/basic-bot.md
    - "📨 Message Handlers": examples/message-handler.md
    - "🎨 Rich Embeds": examples/embeds.md
    - "📝 Logging Setup": examples/logging.md
  - "📚 API Reference":
    - "🔌 Client": api/client.md
  - "🎨 Brand Assets": assets.md
  - "🔧 Troubleshooting": troubleshooting.md
