[package]
name = "message_handler_example"
version = "0.1.0"
edition = "2021"

[dependencies]
rustycord = { path = "../../rustycord" }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
log = "0.4"
env_logger = "0.10"
