[package]
name = "prefix_commands"
version = "0.1.0"
edition = "2021"

[dependencies]
rustycord = "0.1.5"
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1"
log = "0.4"
dotenv = "0.15"
